[package]
name = "bevy_sefirot_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0"

[dependencies.syn]
version = "2.0"
features = ["full"]

[dev-dependencies]
prettyplease = "0.2.15"
