[package]
name = "sefirot_testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
sefirot = { path = "../sefirot" }
winit = "0.29.15"

[dependencies.luisa_compute]
git = "https://github.com/LuisaGroup/luisa-compute-rs"
branch = "main"
